cmake_minimum_required(VERSION 4.3.2)
project(litedb VERSION 0.6.0 LANGUAGES CXX)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(cmake/asio.cmake)

add_subdirectory(internal/src/memory)
add_subdirectory(internal/src/core/parser)
add_subdirectory(internal/src/core/meta)
add_subdirectory(internal/src/core/schema)
add_subdirectory(internal/src/core/function)
add_subdirectory(internal/src/core/index)
add_subdirectory(internal/src/core/vindex)
add_subdirectory(internal/src/core/storage)
add_subdirectory(internal/src/core/filesystem)
add_subdirectory(internal/src/core/io)
add_subdirectory(internal/src/core/binder)
add_subdirectory(internal/src/core/logical_plan)
add_subdirectory(internal/src/core/evaluator)
add_subdirectory(internal/src/core/optimizer)
add_subdirectory(internal/src/core/physical_plan)
add_subdirectory(internal/src/core/executor)
add_subdirectory(internal/src/core/database)
add_subdirectory(internal/src/protocol)
add_subdirectory(internal/src/net)
add_subdirectory(internal/src/server)
add_subdirectory(internal/src/client)

option(LITEDB_BUILD_EXAMPLES "Build LiteDB examples" ON)
if(LITEDB_BUILD_EXAMPLES)
    add_subdirectory(examples)
endif()

enable_testing()
add_subdirectory(tests)
