add_subdirectory(parser)
add_subdirectory(catalog)
add_subdirectory(meta)
add_subdirectory(schema)
add_subdirectory(index)
add_subdirectory(vindex)
add_subdirectory(storage)
add_subdirectory(filesystem)
add_subdirectory(binder)
add_subdirectory(logical_plan)
add_subdirectory(evaluator)
add_subdirectory(optimizer)
add_subdirectory(physical_plan)
add_subdirectory(executor)
add_subdirectory(engine)
add_subdirectory(persistence)
