add_subdirectory(error)
add_subdirectory(parser)
add_subdirectory(catalog)
add_subdirectory(schema)
add_subdirectory(function)
add_subdirectory(index)
add_subdirectory(vindex)
add_subdirectory(storage)
add_subdirectory(filesystem)
add_subdirectory(io)
add_subdirectory(wal)
add_subdirectory(transaction)
add_subdirectory(binder)
add_subdirectory(logical_planner)
add_subdirectory(evaluator)
add_subdirectory(optimizer)
add_subdirectory(physical_planner)
add_subdirectory(executor)
add_subdirectory(database)
