add_executable(protocol_frame_codec_tests
    protocol_frame_codec_tests.cpp
)

target_link_libraries(protocol_frame_codec_tests PRIVATE litedb_protocol)

add_test(NAME protocol_frame_codec_tests COMMAND protocol_frame_codec_tests)

add_executable(protocol_message_codec_tests
    protocol_message_codec_tests.cpp
)

target_link_libraries(protocol_message_codec_tests PRIVATE litedb_protocol)

add_test(NAME protocol_message_codec_tests COMMAND protocol_message_codec_tests)
